version: "3"

services:
  app:
    container_name: next-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    tty: true
    # command: sh -c "cd Next_Tutorial-next && npm run dev"
    ports:
      - "3000:3000"